# Generated by Django 4.1 on 2022-08-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='routineday',
            name='routine',
            field=models.ManyToManyField(related_name='days', to='routine_app.routine'),
        ),
        migrations.AlterField(
            model_name='routineresult',
            name='routine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='routine_app.routine'),
        ),
    ]
