# Generated by Django 4.1 on 2022-08-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='my_user',
        ),
    ]
