# Generated by Django 4.1 on 2022-08-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0002_alter_myuser_managers_alter_routineday_routine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
    ]
