# Generated by Django 4.1 on 2022-08-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0003_remove_myuser_is_staff_remove_myuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
