# Generated by Django 4.1 on 2022-08-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0004_myuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='routineresult',
            name='routine',
        ),
        migrations.AddField(
            model_name='routineresult',
            name='routine',
            field=models.ManyToManyField(related_name='result', to='routine_app.routine'),
        ),
    ]
