# Generated by Django 4.1 on 2022-08-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0005_alter_myuser_is_admin_remove_routineresult_routine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineday',
            name='routine',
            field=models.ManyToManyField(to='routine_app.routine'),
        ),
        migrations.AlterField(
            model_name='routineresult',
            name='routine',
            field=models.ManyToManyField(to='routine_app.routine'),
        ),
    ]
