# Generated by Django 4.1 on 2022-08-23 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0006_alter_routineday_routine_alter_routineresult_routine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineday',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='routineresult',
            name='routine',
        ),
        migrations.AddField(
            model_name='routineday',
            name='routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='routine_app.routine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routineresult',
            name='routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='routine_app.routine'),
            preserve_default=False,
        ),
    ]
