# Generated by Django 4.1 on 2022-08-24 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0008_routineday_result_alter_routineday_routine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineday',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='routine_app.routine'),
        ),
    ]
