# Generated by Django 4.1 on 2022-08-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0009_alter_routineday_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineday',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_app.routine'),
        ),
    ]
